# Generated by Django 4.0.3 on 2022-03-29 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('body', models.TextField()),
                ('number', models.IntegerField()),
                ('created_by', models.ForeignKey(help_text='Creator of this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Creator of this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Updator of this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'db_table': 'journal',
            },
        ),
        migrations.CreateModel(
            name='ChapterViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_views', to='journal.chapter')),
                ('viewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_viewed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter View',
                'verbose_name_plural': 'Chapter Views',
                'db_table': 'chapter_view',
            },
        ),
        migrations.CreateModel(
            name='ChapterLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_likes', to='journal.chapter')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_liked_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter Like',
                'verbose_name_plural': 'Chapter Likes',
                'db_table': 'chapter_like',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_chapters', to='journal.journal'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_by',
            field=models.ForeignKey(help_text='Updator of this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
