# Generated by Django 4.0.3 on 2022-04-04 02:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_journal_is_public'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapterlikes',
            unique_together={('liked_by', 'chapter')},
        ),
    ]
